CREATE TABLE IF NOT EXISTS user (
id_user TINYINT PRIMARY KEY CHECK (id_user = 1),
email VARCHAR(255) UNIQUE NOT NULL,
password_hash VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS blog (
id_blog INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
title VARCHAR(255) NOT NULL,
content TEXT NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
id_user TINYINT NOT NULL,
FOREIGN KEY (id_user) REFERENCES user(id_user)
);


CREATE TABLE IF NOT EXISTS image (
id_image INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
path VARCHAR(255) NOT NULL,
alt_text VARCHAR(255),
id_blog INT,
FOREIGN KEY (id_blog) REFERENCES blog(id_blog)
);
